### ISSUE TITLE
umbrella apps config

### ISSUE THREAD

**Issue by tim2CF** [whitfin/local-cluster#11]
I see that application configs are passed to spawned nodes here
https://github.com/whitfin/local-cluster/blob/f86e6f043c0d58a2ea7bb44f7185a54a3694b949/lib/local_cluster.ex#L70
And looks like it works, but sometimes in my umbrella project some applications are terminating because of missing configs. I have 2 suggestions

- some umbrella app somehow is getting started before this line is executed https://github.com/whitfin/local-cluster/blob/f86e6f043c0d58a2ea7bb44f7185a54a3694b949/lib/local_cluster.ex#L70

- some umbrella app is not loaded (and loading later with missing config) https://github.com/whitfin/local-cluster/blob/f86e6f043c0d58a2ea7bb44f7185a54a3694b949/lib/local_cluster.ex#L68

is it possible?

**Comment by tim2CF** [comment]
can this be relevant?
https://github.com/VoiSmart/local-cluster/commit/b7fa532e71ce414c90788f3d109610751c7c9099

**Comment by whitfin** [comment]
I think this is related to https://github.com/whitfin/local-cluster/issues/13 which is resolved by #15. It should be fixed in the next release (or current master). I'm going to close this, but feel free to re-open if you still have issues!
